config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "messages#index"

  resources :users, only: [:new, :create, :show]
  resources :messages, only: [:index, :create]
  resources :sessions, only: [:create]
  resources :ratings, only: [:create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :ratings
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_one :message
  has_one :user

  validates_uniqueness_of :message_id, :scope => :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :ratings

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, :email_format => { :message => 'Invalid email specified!' }

  # Function that takes entered email and password and either permits or denies
  # user authentication. Compares hash of password against stored user
  # password_hash.
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  # before_save function that hashes specified password if one is given.
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user

  private
  # Helper method to access current user in views.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET /messages
  def index
    @messages = Message.all
    @message = Message.new
  end

  # POST /messages
  def create
    @messages = Message.all
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    respond_to do |format|
      if @message.save
        format.js   {}
      end
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :user_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  before_action :set_rating, only: [:destroy]

  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # POST /ratings
  def create
    @messages = Message.all
    @rating = Rating.new
    @rating.user_id = current_user.id
    @rating.message_id = params[:message_id]
    respond_to do |format|
      if @rating.save
        format.js   {}
      end
    end
  end

  # DELETE /ratings/1
  def destroy
    @messages = Message.all
    @rating.destroy
    respond_to do |format|
      format.js   {}
    end
  end

  private
    def set_rating
      @rating = Rating.find(params[:id])
    end

    def rating_params
      params.require(:rating).permit(:message_id, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/log_in"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/[:id]
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to "/log_in" }
      else
        format.html { render :new }
      end
    end
    end

  private

    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Rails Messenger", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>
            <li class="has-dropdown">
              <%= link_to current_user.email, current_user %>
              <ul class="dropdown">
                <li><%= link_to "Log out", log_out_path %></li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to "Sign up", sign_up_path %>
            </li>
            <li>
              <%= link_to "Log in", log_in_path %>
            </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

<%= yield %>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/messages/_form.html.erb
<!--Form for entering a new message.-->
<%= form_for(@message, remote: true) do |f| %>
  <div class="area">
    <%= f.text_area :content, :placeholder => "Enter your message here" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "button tiny" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<!--This view is rendered for each message.-->
<div class="row">
  <div class="small-2 columns"><%= message.user.email %> wrote:</div>
  <div class="small-8 columns"><%= message.content %></div>
  <div class="small-1 columns"><%= message.ratings.count %> points</div>
  <div class="small-1 columns button-container">
    <!--Display vote/unvote buttons if current_user is set (user is logged in)-->
    <% if current_user %>
        <!--
        Show unvote button if current_user has voted for this message, OR
        Show vote button if current_user has not voted for this message yet.
        -->
        <% if rating = current_user.ratings.find_by(message_id: message.id) %>
            <%= button_to "-1", rating_path(rating.id, :message_id => message.id), :method => :delete, :remote => true, :class => "button tiny button-vote" %>
        <% else %>
            <%= button_to "+1", ratings_path(:message_id => message.id), :method => :post, :remote => true, :class => "button tiny button-vote" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/messages/create.js.erb
$("#messages").html("<%= escape_javascript(render :partial => @messages.reverse) %>");

document.getElementById("message_content").value = "";
document.getElementById("message_content").focus();

app/views/messages/index.html.erb
<!-- Main index page for root_path. -->
<div class="row">
  <h2>Messages</h2>
  <div class="message-container">
    <ul id="messages">
      <!-- Render _message.html.erb for each message. Reverse the order
      to show the most resent message on top. -->
      <%= render :partial => @messages.reverse %>
    </ul>
  </div>
  <div class="add-message-container">
    <!-- If current_user is set show new message form else link to sign up or log in -->
    <% if current_user %>
        <h3>Add new message</h3>
        <%= render 'form' %>
    <% else %>
        <p>
            <%= link_to "Log in", log_in_path %> (or <%= link_to "sign up", sign_up_path %>) to join the fun!
        </p>
    <% end %>
  </div>
</div>

app/views/ratings/create.js.erb
// JavaScript file to handle response from ratings_controller when new rating has been made.
// Re-render all messages to update the message list with new rating.
// TODO: Only re-render specific message for which the rating was made.
$("#messages").html("<%= escape_javascript(render :partial => @messages.reverse) %>");

app/views/ratings/destroy.js.erb
// JavaScript file to handle response from ratings_controller when a rating has been destroyed.
// Re-render all messages to update the message list with removed rating.
// TODO: Only re-render specific message for which the rating was destroyed.
$("#messages").html("<%= escape_javascript(render :partial => @messages.reverse) %>");

app/views/users/_form.html.erb
<!-- Form for user to sign up. -->
<%= form_for(@user) do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <div class="actions">
      <%= f.submit "Submit", :class => "button tiny" %>
    </div>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="small-3 small-centered columns">
    <h1>Sign up</h1>
    <br/>
    <!-- Renders the sign up form. -->
    <%= render 'form' %>

  </div>
</div>

app/views/users/show.html.erb
<!-- View to show current_user's messages. -->
<div class="row">
    <h2>Sent messages</h2>
    <ul id="messages">
      <!-- for each of current_user's messages... -->
      <% for message in current_user.messages %>
          <li>
            <div class="small-10 columns"><%= message.content %></div>
            <div class="small-2 columns"><%= message.ratings.count %> points</div>
          </li>
      <% end %>
    </ul>
</div>